### PR TITLE
feat: add search bar and filter checkboxes 

### PR DESCRIPTION
**Pull request by aminya**
Default: 

image

Filtering:

image

Search:

search

### CODE REVIEW

**Comment by kelteseth** [comment]
Wow that is actually pretty neat, good job! I just pushed some small changes, please check if everything is still working :)

**Comment by aminya** [comment]
@kelteseth Thank you!

Yes, rebased and tested. it works. We could make the size of the columns fixed to avoid shrinking of the table when filtering happens, but that's a minor thing that can be fixed later.

**Comment by kelteseth** [comment]
Thanks, I will fix some of the styling issues (I created 😊). Great PR!

**Comment by kelteseth** [comment]
@aminya If you have the time, you could add a separate sort button for the help wanted option :)

**Comment by aminya** [comment]
No worries. Check out #21!

**Pull request merged**
